// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/convocazioni" | "/app/convocazioni/[id]" | "/app/debug" | "/app/eventi" | "/app/eventi/[id]" | "/app/eventi/[id]/risposte" | "/app/giocatori" | "/app/impostazioni" | "/app/logout" | "/app/staff" | "/chi-siamo" | "/contatti" | "/galleria-immagini" | "/imposta-password" | "/login" | "/notizie" | "/servizi" | "/stagione-agonistica-25-26" | "/team"
type AppRouteHandlerRoutes = "/api/contatti" | "/api/places/autocomplete" | "/api/places/details" | "/api/players/create" | "/api/staff/create" | "/api/staff/delete" | "/api/staff/list" | "/api/staff/update"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contatti": {}
  "/api/places/autocomplete": {}
  "/api/places/details": {}
  "/api/players/create": {}
  "/api/staff/create": {}
  "/api/staff/delete": {}
  "/api/staff/list": {}
  "/api/staff/update": {}
  "/app": {}
  "/app/convocazioni": {}
  "/app/convocazioni/[id]": { "id": string; }
  "/app/debug": {}
  "/app/eventi": {}
  "/app/eventi/[id]": { "id": string; }
  "/app/eventi/[id]/risposte": { "id": string; }
  "/app/giocatori": {}
  "/app/impostazioni": {}
  "/app/logout": {}
  "/app/staff": {}
  "/chi-siamo": {}
  "/contatti": {}
  "/galleria-immagini": {}
  "/imposta-password": {}
  "/login": {}
  "/notizie": {}
  "/servizi": {}
  "/stagione-agonistica-25-26": {}
  "/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
