// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/app/convocazioni/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/convocazioni/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/app/convocazioni/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/convocazioni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/convocazioni">> = Specific
  const handler = {} as typeof import("../../../src/app/app/convocazioni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/debug">> = Specific
  const handler = {} as typeof import("../../../src/app/app/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/eventi/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/eventi/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/app/eventi/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/eventi/[id]/risposte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/eventi/[id]/risposte">> = Specific
  const handler = {} as typeof import("../../../src/app/app/eventi/[id]/risposte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/eventi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/eventi">> = Specific
  const handler = {} as typeof import("../../../src/app/app/eventi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/giocatori/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/giocatori">> = Specific
  const handler = {} as typeof import("../../../src/app/app/giocatori/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/impostazioni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/impostazioni">> = Specific
  const handler = {} as typeof import("../../../src/app/app/impostazioni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/app/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/chi-siamo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chi-siamo">> = Specific
  const handler = {} as typeof import("../../../src/app/chi-siamo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contatti/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contatti">> = Specific
  const handler = {} as typeof import("../../../src/app/contatti/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/galleria-immagini/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galleria-immagini">> = Specific
  const handler = {} as typeof import("../../../src/app/galleria-immagini/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/imposta-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imposta-password">> = Specific
  const handler = {} as typeof import("../../../src/app/imposta-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notizie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notizie">> = Specific
  const handler = {} as typeof import("../../../src/app/notizie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/servizi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servizi">> = Specific
  const handler = {} as typeof import("../../../src/app/servizi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stagione-agonistica-25-26/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stagione-agonistica-25-26">> = Specific
  const handler = {} as typeof import("../../../src/app/stagione-agonistica-25-26/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../../src/app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contatti/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contatti">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contatti/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/places/autocomplete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places/autocomplete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/places/autocomplete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/places/details/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places/details">> = Specific
  const handler = {} as typeof import("../../../src/app/api/places/details/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/players/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/players/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/players/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/delete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/update">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
